CREATE TABLE IF NOT EXISTS Products
(
  Id         SERIAL PRIMARY KEY,
  Code       VARCHAR(50) NOT NULL UNIQUE,
  Name       VARCHAR(100) NOT NULL,
  CreateDate TIMESTAMP NOT NULL,
  LastUpdate TIMESTAMP NOT NULL,
  IsActive   BOOLEAN,
  IsDeleted  BOOLEAN
);