CREATE TABLE IF NOT EXISTS Skus
(
  Id         SERIAL PRIMARY KEY,
  Code       VARCHAR(50) NOT NULL UNIQUE,
  Name       VARCHAR(100) NOT NULL,
  ProductId  BIGINT UNSIGNED NOT NULL,
  CreateDate TIMESTAMP NOT NULL,
  LastUpdate TIMESTAMP NOT NULL,
  IsActive   BOOLEAN NOT NULL,
  IsDeleted  BOOLEAN NOT NULL,
  FOREIGN KEY (ProductId) REFERENCES Products(Id)
);